version: "3.5"

volumes:
  postgres:

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    network_mode: host

  bot:
    build: .
    container_name: bot
    hostname: bot
    command: python3 /app/src/main.py
    ports:
      - "7001:7001"
    depends_on:
      - "postgres"
    env_file:
      - ./.env
    network_mode: "host"