version: "3.5"

volumes:
  postgresdb:

services:

  postgresdb:
    image: postgres:latest
    container_name: postgres_helper
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - ./postgresdb:/var/lib/postgresql/data
    network_mode: host